"""auto_migration

Revision ID: 39b02a7bb6b0
Revises: 9685b332cf03
Create Date: 2026-05-15 12:07:59.125606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '39b02a7bb6b0'
down_revision: Union[str, None] = '9685b332cf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'last_seen_utc')
    op.drop_column('networks', 'cpu_limit')
    op.drop_column('networks', 'memory_limit_mb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('memory_limit_mb', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('networks', sa.Column('cpu_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('networks', sa.Column('last_seen_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
