"""auto_migration

Revision ID: 838f50d269a9
Revises: 
Create Date: 2026-05-11 17:32:06.663307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '838f50d269a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DRAINING', name='host_status_enum'), nullable=False),
    sa.Column('cpu_total', sa.Integer(), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_hosts_hostname'), 'hosts', ['hostname'], unique=True)
    op.create_table('labs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'FAILED', name='lab_status_enum'), nullable=False),
    sa.Column('cpu_total', sa.Integer(), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_host_id'), 'labs', ['host_id'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'STARTED', 'STOPPED', 'PAUSED', 'FAILED', name='container_status_enum'), nullable=False),
    sa.Column('cpu_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('lifetime_type', sa.Enum('PERSISTENT', 'EPHEMERAL', 'SINGLE_USE', 'SESSION', name='lifetime_type_enum'), nullable=False),
    sa.Column('time_to_live_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('last_seen_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_id')
    )
    op.create_index(op.f('ix_containers_lab_id'), 'containers', ['lab_id'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Enum('BRIDGE', 'OVERLAY', name='network_driver_enum'), nullable=False),
    sa.Column('cpu_limit', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('last_seen_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id')
    )
    op.create_index(op.f('ix_networks_lab_id'), 'networks', ['lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networks_lab_id'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_containers_lab_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_labs_host_id'), table_name='labs')
    op.drop_table('labs')
    op.drop_index(op.f('ix_hosts_hostname'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
