"""auto_migration

Revision ID: 9685b332cf03
Revises: 7e2d93b91f0f
Create Date: 2026-05-15 11:49:02.155853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9685b332cf03'
down_revision: Union[str, None] = '7e2d93b91f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'time_to_live_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hosts', 'port',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('hosts', 'scheme',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.drop_column('labs', 'memory_total_mb')
    op.drop_column('labs', 'cpu_total')
    op.alter_column('projects', 'compose_file',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'pull',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'build',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'build',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('projects', 'pull',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('projects', 'compose_file',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'docker-compose.yml'::character varying"),
               existing_nullable=False)
    op.add_column('labs', sa.Column('cpu_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('labs', sa.Column('memory_total_mb', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('hosts', 'scheme',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'http'::character varying"),
               existing_nullable=False)
    op.alter_column('hosts', 'port',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8000'),
               existing_nullable=False)
    op.alter_column('containers', 'time_to_live_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
