DATABASE_URL_ENV_VAR = "DB_URL"

VAULT_ADDR_ENV_VAR = "VAULT_ADDR"
VAULT_TOKEN_ENV_VAR = "VAULT_TOKEN"
VAULT_KV_MOUNT_ENV_VAR = "VAULT_KV_MOUNT"
VAULT_KV_MOUNT_DEFAULT = "secret"

LAB_HOST_API_KEY_HEADER = "X-API-Key"
LAB_HOST_REQUEST_TIMEOUT_SECONDS = 15.0

DEPLOYMENT_TYPE_ENV_VAR = "DEPLOYMENT_TYPE"

DNS_PROVIDER_BASE_URL_ENV_VAR = "DNS_PROVIDER_BASE_URL"
DNS_PROVIDER_TOKEN_ENV_VAR = "DNS_PROVIDER_TOKEN"
DNS_PROVIDER_FILE_ENV_VAR = "DNS_PROVIDER_FILE"

INGRESS_PROVIDER_BASE_URL_ENV_VAR = "INGRESS_PROVIDER_BASE_URL"
INGRESS_PROVIDER_TOKEN_ENV_VAR = "INGRESS_PROVIDER_TOKEN"
INGRESS_PROVIDER_FILE_ENV_VAR = "INGRESS_PROVIDER_FILE"

PROVIDER_REQUEST_TIMEOUT_SECONDS = 10.0
