DATABASE_URL_ENV_VAR = "DB_URL"

VAULT_ADDR_ENV_VAR = "VAULT_ADDR"
VAULT_TOKEN_ENV_VAR = "VAULT_TOKEN"
VAULT_KV_MOUNT_ENV_VAR = "VAULT_KV_MOUNT"
VAULT_KV_MOUNT_DEFAULT = "secret"

LAB_HOST_API_KEY_HEADER = "X-API-Key"
LAB_HOST_REQUEST_TIMEOUT_SECONDS = 15.0
